alias: 049 - Set ventilation to high
trigger:
  platform: state
  entity_id: sensor.wants_mv
condition:
  condition: state
  entity_id: sensor.wants_mv
  state: 'high'
action:
  - service: switch.turn_on
    entity_id: 
      - switch.havc_high
  - service: switch.turn_off
    entity_id: 
      - switch.havc_middle
