alias: 'record cumulative enery production to midnight'
trigger:
  - platform: time
    at: "00:00:01"
action:
  service: mqtt.publish
  data_template:
    topic: 'ha/cum_energy_production_prior'
    retain: true
    payload: '{"day_1":"{{((states.sensor.huidig_verbruik.attributes["powerProductionHighTariff"] / 1000)  + (states.sensor.huidig_verbruik.attributes["powerProductionLowTariff"] / 1000)) | round(1) }}"}'
