alias: 'record cumulative enery usage to midnight'
trigger:
  - platform: time
    at: "00:00:01"
action:
  service: mqtt.publish
  data_template:
    topic: 'ha/cum_energy_usage_prior'
    retain: true
    payload: '{"day_1":"{{(float(states.sensor.power_consumption_low_tariff.state)  + float(states.sensor.power_consumption_high_tariff.state)) | round(1) }}"}'
