alias: Ventilation - shower - set high
trigger:
  platform: numeric_state
  entity_id: sensor.temp_water_shower
  above: 30
action:
  service: input_select.select_option
  data:
    entity_id: input_select.wants_mv_hum_bdk
    option: 'Hoog'
